name: Playwright Tests

on:
  pull_request:

jobs:
  e2e-tests:
    name: Run Playwright tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - maze-compiler
          - maze-robot
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: ${{ matrix.project }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ matrix.project }}

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ${{ matrix.project }}

      - name: Run Playwright tests
        run: npm run test:e2e
        working-directory: ${{ matrix.project }}
